# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a74cd9a0aa38157eb0908e49f1355c0033e590033ec1c219863e5f81d57855c0c96d5e27b74ac43c4f93aa10d85fb1196861ac1dd5ae9b8cf55b773974cfb950

test:
  secret_key_base: a79f2b1da5a179d6a99a3bc13abe83483cc57b1f308b0064452f63f789eb6ade9042a2ad6a47b7230a45fe6f542b5f0f5d55619bb2be7c5111a450842d3d8d26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
